/* eslint-disable react/no-unknown-property */
/* eslint-disable import/no-extraneous-dependencies */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable @typescript-eslint/consistent-type-imports */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: timblewee (https://sketchfab.com/timblewee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/train-br-class-08-shunter-swallow-livery-a9dfe904aee048e196c5caae1d6b2b85
Title: Train - BR Class 08 Shunter Swallow Livery
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_33: THREE.Mesh
    Object_34: THREE.Mesh
    Object_35: THREE.Mesh
    Object_37: THREE.Mesh
    Object_38: THREE.Mesh
    Object_39: THREE.Mesh
    Object_41: THREE.Mesh
    Object_43: THREE.Mesh
    Object_44: THREE.Mesh
    Object_45: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_49: THREE.Mesh
    Object_50: THREE.Mesh
    Object_51: THREE.Mesh
    Object_52: THREE.Mesh
    Object_53: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_58: THREE.Mesh
    Object_60: THREE.Mesh
    Object_61: THREE.Mesh
    Object_62: THREE.Mesh
    Object_63: THREE.Mesh
    Object_65: THREE.Mesh
    Object_66: THREE.Mesh
    Object_68: THREE.Mesh
    Object_69: THREE.Mesh
    Object_71: THREE.Mesh
    Object_73: THREE.Mesh
    Object_75: THREE.Mesh
    Object_76: THREE.Mesh
    Object_77: THREE.Mesh
    Object_78: THREE.Mesh
    Object_79: THREE.Mesh
    Object_81: THREE.Mesh
    Object_82: THREE.Mesh
    Object_84: THREE.Mesh
    Object_85: THREE.Mesh
    Object_87: THREE.Mesh
    Object_89: THREE.Mesh
    Object_91: THREE.Mesh
    Object_93: THREE.Mesh
    Object_94: THREE.Mesh
    Object_96: THREE.Mesh
    Object_97: THREE.Mesh
    Object_98: THREE.Mesh
    Object_99: THREE.Mesh
    Object_100: THREE.Mesh
    Object_102: THREE.Mesh
    Object_104: THREE.Mesh
    Object_106: THREE.Mesh
    Object_108: THREE.Mesh
    Object_110: THREE.Mesh
    Object_112: THREE.Mesh
    Object_114: THREE.Mesh
    Object_116: THREE.Mesh
    Object_117: THREE.Mesh
    Object_119: THREE.Mesh
    Object_120: THREE.Mesh
    Object_121: THREE.Mesh
    Object_122: THREE.Mesh
    Object_124: THREE.Mesh
    Object_125: THREE.Mesh
    Object_127: THREE.Mesh
    Object_129: THREE.Mesh
    Object_131: THREE.Mesh
    Object_133: THREE.Mesh
    Object_135: THREE.Mesh
    Object_137: THREE.Mesh
    Object_139: THREE.Mesh
    Object_141: THREE.Mesh
    Object_142: THREE.Mesh
    Object_143: THREE.Mesh
    Object_145: THREE.Mesh
    Object_147: THREE.Mesh
    Object_149: THREE.Mesh
    Object_151: THREE.Mesh
    Object_152: THREE.Mesh
    Object_154: THREE.Mesh
    Object_156: THREE.Mesh
    Object_157: THREE.Mesh
    Object_159: THREE.Mesh
    Object_161: THREE.Mesh
    Object_163: THREE.Mesh
    Object_165: THREE.Mesh
    Object_167: THREE.Mesh
    Object_169: THREE.Mesh
    Object_171: THREE.Mesh
    Object_173: THREE.Mesh
    Object_174: THREE.Mesh
    Object_176: THREE.Mesh
    Object_177: THREE.Mesh
    Object_178: THREE.Mesh
    Object_180: THREE.Mesh
    Object_181: THREE.Mesh
    Object_182: THREE.Mesh
    Object_184: THREE.Mesh
    Object_186: THREE.Mesh
    Object_188: THREE.Mesh
    Object_190: THREE.Mesh
    Object_192: THREE.Mesh
    Object_194: THREE.Mesh
    Object_196: THREE.Mesh
    Object_198: THREE.Mesh
    Object_200: THREE.Mesh
    Object_202: THREE.Mesh
    Object_204: THREE.Mesh
    Object_206: THREE.Mesh
    Object_209: THREE.Mesh
    Object_211: THREE.Mesh
    Object_213: THREE.Mesh
    Object_215: THREE.Mesh
  }
  materials: {
    Roof_Black: THREE.MeshStandardMaterial
    Wheels: THREE.MeshStandardMaterial
    ['Button_Silver.001']: THREE.MeshStandardMaterial
    Body: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    Yellow: THREE.MeshStandardMaterial
    Black_Paint: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Cream: THREE.MeshStandardMaterial
    ['Yellow.001']: THREE.MeshStandardMaterial
    Button_Silver: THREE.MeshStandardMaterial
    ['Glass.001']: THREE.MeshStandardMaterial
    Silver_Gold: THREE.MeshStandardMaterial
    ['Button_Silver.002']: THREE.MeshStandardMaterial
    ['Wheels.002']: THREE.MeshStandardMaterial
    ['Roof_Black.003']: THREE.MeshStandardMaterial
    ['Roof_Black.002']: THREE.MeshStandardMaterial
    Black_Plastic: THREE.MeshStandardMaterial
    Copper: THREE.MeshStandardMaterial
    ['White.001']: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Red.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFActions[];
};

type ActionName = 'Animation';
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    '/train_-_br_class_08_shunter_swallow_livery.glb'
  ) as GLTFResult;
  // @ts-ignore
  const { actions } = useAnimations(animations, group);
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Wheels_0" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.Roof_Black}
                />
                <mesh
                  name="Object_5"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_5.geometry}
                  material={materials.Wheels}
                />
              </group>
              <group name="Buffers_1" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_7"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials['Button_Silver.001']}
                />
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group name="Main_Body_2" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.Body}
                />
                <mesh
                  name="Object_11"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_11.geometry}
                  material={materials.Glass}
                />
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials.Roof_Black}
                />
                <mesh
                  name="Object_13"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials.White}
                />
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.Yellow}
                />
                <mesh
                  name="Object_15"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_15.geometry}
                  material={materials.Wheels}
                />
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.Black_Paint}
                />
                <mesh
                  name="Object_17"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_17.geometry}
                  material={materials.material}
                />
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.Cream}
                />
              </group>
              <group name="Undercarriage_Skirt_3" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group name="Axel_Hubs_4" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.Wheels}
                />
                <mesh
                  name="Object_23"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_23.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group name="Wishbone_Suspension_5" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_25"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_25.geometry}
                  material={materials.Wheels}
                />
                <mesh
                  name="Object_26"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group name="Suspension_Mounts_6" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_28"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials.Wheels}
                />
              </group>
              <group name="Skirt_Rovets_7" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials.Wheels}
                />
              </group>
              <group name="Side_Panel_Doors_8" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_32"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={materials.Body}
                />
                <mesh
                  name="Object_33"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_33.geometry}
                  material={materials.White}
                />
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials.material}
                />
                <mesh
                  name="Object_35"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_35.geometry}
                  material={materials.Cream}
                />
              </group>
              <group name="Oval_Covers_9" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_37"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_37.geometry}
                  material={materials.Body}
                />
                <mesh
                  name="Object_38"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials.material}
                />
                <mesh
                  name="Object_39"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_39.geometry}
                  material={materials.Cream}
                />
              </group>
              <group name="Box_Tops001_10" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_41"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_41.geometry}
                  material={materials.Body}
                />
              </group>
              <group name="Vented_side_Doors_11" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_43"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_43.geometry}
                  material={materials.Body}
                />
                <mesh
                  name="Object_44"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials.White}
                />
                <mesh
                  name="Object_45"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_45.geometry}
                  material={materials.material}
                />
                <mesh
                  name="Object_46"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials.Cream}
                />
              </group>
              <group name="Rivets_12" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_48"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={materials.Body}
                />
                <mesh
                  name="Object_49"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_49.geometry}
                  material={materials.Cream}
                />
                <mesh
                  name="Object_50"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_50.geometry}
                  material={materials.White}
                />
                <mesh
                  name="Object_51"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_51.geometry}
                  material={materials.material}
                />
                <mesh
                  name="Object_52"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_52.geometry}
                  material={materials.Yellow}
                />
                <mesh
                  name="Object_53"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_53.geometry}
                  material={materials['Yellow.001']}
                />
                <mesh
                  name="Object_54"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_54.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group name="Knob_13" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_56"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_56.geometry}
                  material={materials.Cream}
                />
              </group>
              <group name="Hinges_Rear_Grille_14" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_58"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_58.geometry}
                  material={materials['Yellow.001']}
                />
              </group>
              <group name="Small_Side_Boxes_15" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_60"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_60.geometry}
                  material={materials.Body}
                />
                <mesh
                  name="Object_61"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_61.geometry}
                  material={materials.White}
                />
                <mesh
                  name="Object_62"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_62.geometry}
                  material={materials.material}
                />
                <mesh
                  name="Object_63"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_63.geometry}
                  material={materials.Cream}
                />
              </group>
              <group name="Hinges_16" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_65"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_65.geometry}
                  material={materials.Body}
                />
                <mesh
                  name="Object_66"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_66.geometry}
                  material={materials.Cream}
                />
              </group>
              <group name="Sides_Rails_17" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_68"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_68.geometry}
                  material={materials.White}
                />
                <mesh
                  name="Object_69"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_69.geometry}
                  material={materials.Body}
                />
              </group>
              <group name="Side_Rails_Long_Top_18" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_71"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_71.geometry}
                  material={materials.White}
                />
              </group>
              <group name="Box_Tops_19" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_73"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_73.geometry}
                  material={materials.Body}
                />
              </group>
              <group name="Side_Grilles_20" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_75"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_75.geometry}
                  material={materials.Body}
                />
                <mesh
                  name="Object_76"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_76.geometry}
                  material={materials.Roof_Black}
                />
                <mesh
                  name="Object_77"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_77.geometry}
                  material={materials.White}
                />
                <mesh
                  name="Object_78"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_78.geometry}
                  material={materials.material}
                />
                <mesh
                  name="Object_79"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_79.geometry}
                  material={materials.Cream}
                />
              </group>
              <group name="Latches_21" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_81"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_81.geometry}
                  material={materials.Body}
                />
                <mesh
                  name="Object_82"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_82.geometry}
                  material={materials.Cream}
                />
              </group>
              <group name="Hinges001_22" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_84"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_84.geometry}
                  material={materials.Body}
                />
                <mesh
                  name="Object_85"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_85.geometry}
                  material={materials.Cream}
                />
              </group>
              <group
                name="Door_Handles_by_Helindu_Downloaded_from_Sketchfab_23"
                position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_87"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_87.geometry}
                  material={materials.Button_Silver}
                />
              </group>
              <group name="Pipe_24" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_89"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_89.geometry}
                  material={materials.Wheels}
                />
              </group>
              <group name="Axel_Hubs001_25" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_91"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_91.geometry}
                  material={materials.Wheels}
                />
              </group>
              <group name="Clock_26" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_93"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_93.geometry}
                  material={materials['Glass.001']}
                />
                <mesh
                  name="Object_94"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_94.geometry}
                  material={materials.Body}
                />
              </group>
              <group name="Taps_and_Pipes_27" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_96"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_96.geometry}
                  material={materials.Silver_Gold}
                />
                <mesh
                  name="Object_97"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_97.geometry}
                  material={materials['Button_Silver.002']}
                />
                <mesh
                  name="Object_98"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_98.geometry}
                  material={materials.Roof_Black}
                />
                <mesh
                  name="Object_99"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_99.geometry}
                  material={materials.Button_Silver}
                />
                <mesh
                  name="Object_100"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_100.geometry}
                  material={materials.White}
                />
              </group>
              <group name="Undercarriage_Skirt001_28" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_102"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_102.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group name="Undercarriage_Skirt002_29" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_104"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_104.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group name="Bracket_30" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_106"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_106.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group name="Brackets_31" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_108"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_108.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group name="Rear_Tank_32" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_110"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_110.geometry}
                  material={materials.Wheels}
                />
              </group>
              <group name="Front_Tank_33" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_112"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_112.geometry}
                  material={materials.Wheels}
                />
              </group>
              <group name="Coupler_34" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_114"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_114.geometry}
                  material={materials['Wheels.002']}
                />
              </group>
              <group name="Coupler001_35" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_116"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_116.geometry}
                  material={materials['Roof_Black.003']}
                />
                <mesh
                  name="Object_117"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_117.geometry}
                  material={materials['Wheels.002']}
                />
              </group>
              <group name="Sockets_36" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_119"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_119.geometry}
                  material={materials['Yellow.001']}
                />
                <mesh
                  name="Object_120"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_120.geometry}
                  material={materials['Roof_Black.003']}
                />
                <mesh
                  name="Object_121"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_121.geometry}
                  material={materials.Black_Paint}
                />
                <mesh
                  name="Object_122"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_122.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Front_Grill_37" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_124"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_124.geometry}
                  material={materials['Yellow.001']}
                />
                <mesh
                  name="Object_125"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_125.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group name="Front_Grille_Bottom_Deformed_38" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_127"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_127.geometry}
                  material={materials['Yellow.001']}
                />
              </group>
              <group name="Rear_Steps_39" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_129"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_129.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group name="Side_Box_Hinges_40" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_131"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_131.geometry}
                  material={materials.Cream}
                />
              </group>
              <group name="Side_Grilles001_41" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_133"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_133.geometry}
                  material={materials['Yellow.001']}
                />
              </group>
              <group name="Tag_42" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_135"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_135.geometry}
                  material={materials['Yellow.001']}
                />
              </group>
              <group name="Handles_43" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_137"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_137.geometry}
                  material={materials['Yellow.001']}
                />
              </group>
              <group name="Rear_Grill_Lever_44" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_139"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_139.geometry}
                  material={materials['Yellow.001']}
                />
              </group>
              <group name="Front_Tank001_45" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_141"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_141.geometry}
                  material={materials.Wheels}
                />
                <mesh
                  name="Object_142"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_142.geometry}
                  material={materials['Roof_Black.002']}
                />
                <mesh
                  name="Object_143"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_143.geometry}
                  material={materials.White}
                />
              </group>
              <group name="Underside_Things_46" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_145"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_145.geometry}
                  material={materials.Wheels}
                />
              </group>
              <group name="Rear_Tanks_47" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_147"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_147.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group name="Blank_Box_48" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_149"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_149.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group name="Front_Strip_Panel_49">
                <mesh
                  name="Object_151"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_151.geometry}
                  material={materials.Black_Paint}
                />
                <mesh
                  name="Object_152"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_152.geometry}
                  material={materials['Yellow.001']}
                />
              </group>
              <group name="Interior_Filler_Cube_50" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_154"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_154.geometry}
                  material={materials.Black_Plastic}
                />
              </group>
              <group name="Cabin_Interior_51" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_156"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_156.geometry}
                  material={materials.Roof_Black}
                />
                <mesh
                  name="Object_157"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_157.geometry}
                  material={materials.Cream}
                />
              </group>
              <group name="Pipe001_52" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_159"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_159.geometry}
                  material={materials.Copper}
                />
              </group>
              <group name="Pipe002_53" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_161"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_161.geometry}
                  material={materials.Copper}
                />
              </group>
              <group name="Hopper_Pipe_54" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_163"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_163.geometry}
                  material={materials.Wheels}
                />
              </group>
              <group name="Rear_Pipes_55" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_165"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_165.geometry}
                  material={materials['Yellow.001']}
                />
              </group>
              <group name="Nuts_56" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_167"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_167.geometry}
                  material={materials['Yellow.001']}
                />
              </group>
              <group name="Ls_57" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_169"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_169.geometry}
                  material={materials['Yellow.001']}
                />
              </group>
              <group name="Ls001_58" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_171"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_171.geometry}
                  material={materials['Yellow.001']}
                />
              </group>
              <group name="Grille_Thing_59" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_173"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_173.geometry}
                  material={materials['Yellow.001']}
                />
                <mesh
                  name="Object_174"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_174.geometry}
                  material={materials.Black_Plastic}
                />
              </group>
              <group name="Rear_Lights_60" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_176"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_176.geometry}
                  material={materials.Black_Paint}
                />
                <mesh
                  name="Object_177"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_177.geometry}
                  material={materials.Glass}
                />
                <mesh
                  name="Object_178"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_178.geometry}
                  material={materials.Button_Silver}
                />
              </group>
              <group name="Front_Lights_61" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_180"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_180.geometry}
                  material={materials.Black_Paint}
                />
                <mesh
                  name="Object_181"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_181.geometry}
                  material={materials.Glass}
                />
                <mesh
                  name="Object_182"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_182.geometry}
                  material={materials.Button_Silver}
                />
              </group>
              <group name="thing_62" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_184"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_184.geometry}
                  material={materials.Yellow}
                />
              </group>
              <group name="Brass_Pipe_63" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_186"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_186.geometry}
                  material={materials.Copper}
                />
              </group>
              <group name="Brass_Pipe_Front_64" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_188"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_188.geometry}
                  material={materials.Copper}
                />
              </group>
              <group name="BR_Logo_65" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_190"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_190.geometry}
                  material={materials['White.001']}
                />
              </group>
              <group name="Text_66" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_192"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_192.geometry}
                  material={materials.material_0}
                />
              </group>
              <group name="Live_Wire_Sign_67" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_194"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_194.geometry}
                  material={materials.Material}
                />
              </group>
              <group name="Live_Wire_Sign_Front_68" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_196"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_196.geometry}
                  material={materials.Material}
                />
              </group>
              <group name="Text001_70" position={[-0.007, 0, 0]}>
                <mesh
                  name="Object_198"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_198.geometry}
                  material={materials.material_0}
                />
              </group>
              <group name="Wheels001_72" position={[0.792, 0.693, 1.78]}>
                <mesh
                  name="Object_200"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_200.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group name="Wheels002_73" position={[0.799, 0.693, 0.039]}>
                <mesh
                  name="Object_202"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_202.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group name="Wheels003_75" position={[0.805, 0.693, -1.702]}>
                <mesh
                  name="Object_204"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_204.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group name="Connecting_Rod001_76" position={[1.066, 0.466, 1.673]}>
                <mesh
                  name="Object_206"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_206.geometry}
                  material={materials['Red.001']}
                />
              </group>
              <group name="Wheel_Control_78" position={[2.529, -0.105, 0.994]} />
              <group
                name="Wheels004_80"
                position={[-0.812, 0.693, 1.78]}
                rotation={[-Math.PI, 0, -Math.PI]}>
                <mesh
                  name="Object_209"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_209.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group
                name="Wheels005_81"
                position={[-0.806, 0.693, 0.039]}
                rotation={[-Math.PI, 0, -Math.PI]}>
                <mesh
                  name="Object_211"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_211.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group
                name="Wheels006_83"
                position={[-0.8, 0.693, -1.702]}
                rotation={[-Math.PI, 0, -Math.PI]}>
                <mesh
                  name="Object_213"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_213.geometry}
                  material={materials.Roof_Black}
                />
              </group>
              <group name="Connecting_Rod002_84" position={[-1.282, 0.483, 1.916]}>
                <mesh
                  name="Object_215"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_215.geometry}
                  material={materials['Red.001']}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('@/assets/train_-_br_class_08_shunter_swallow_livery.glb');
